### ISSUE TITLE
Dependency for Proximity Prompts cannot be found

### ISSUE THREAD

**Issue by SweetsMarie** [Z3rio/zerio-bcs-heist#2]
Installed the script with the given instructions, made sure it was spelled correctly in manifest and code, lastly made sure the dependencies ran before the script. It still refuses to find proximity prompts. Am I missing something?

**Comment by Z3rio** [comment]
Please show the code you are trying to run when this error happens (show the code calling the export)

**Comment by Z3rio** [comment]
Please make sure that the prompts script is called "zerio-proximityprompt" and not "zerio-proximityprompt**s**" or something like that.
