### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by ReazCho** [Z3rio/zerio-bcs-heist#4]
It wont start , like resource

**Comment by Z3rio** [comment]
What happens upon starting it?

**Comment by ReazCho** [comment]
nothing it wont start . When i check tx admin and hit start nothing ,

**Comment by Z3rio** [comment]
What gets outputted in your console upon starting the resource?

**Comment by ReazCho** [comment]
I dont get anything in console because the scipt wont start  do you want to show you on discord

**Comment by Z3rio** [comment]
Could you screenshot what gets outputted upon running `ensure zerio-bcs-heist` in your server console and send it here, thank you.

**Comment by ReazCho** [comment]
![image](https://github.com/Z3rio/zerio-bcs-heist/assets/115922646/229e7c4b-7059-46f8-8ec5-0a32883c3462)
its just stay like that

**Comment by Z3rio** [comment]
Please do what was asked for above, thank you.

**Comment by ReazCho** [comment]
![image](https://github.com/Z3rio/zerio-bcs-heist/assets/115922646/82052955-a2e4-4e68-ab97-7688694f18bd)
![image](https://github.com/Z3rio/zerio-bcs-heist/assets/115922646/38eee4d8-1818-4082-bf60-6e5e1beabc7b)
here you go screen shot of console

**Comment by ReazCho** [comment]
![image](https://github.com/Z3rio/zerio-bcs-heist/assets/115922646/c758b422-01b8-428b-b223-2c2d49a846a2)

**Comment by Z3rio** [comment]
Looks like you're missing some dependencies, more specifically zerio-proximityprompt.
Or its named something other than `zerio-proximityprompt`.
